### ISSUE TITLE
映像が破綻してしまうのですがプラグインとエンコーダ、どちらの問題でしょうか?

### ISSUE THREAD

**Issue by resistorsytrus** [rigaya/x265guiEx#2]
------------------------------------------------------------------------------------------------------------------------------
[C:\Users\yuuki\Opia.1080i24.mkv]
------------------------------------------------------------------------------------------------------------------------------
auo [info]: x265guiEx 4.17 / Windows 11 x64 (22631) / Intel Xeon(R) E5-2650 v4 @ 2.20GHz [TB: 2.90GHz] (12C/12T)
auo [info]: video: 0:00:20.000 12/1(12.000) fps
auo [info]: audio: 0:00:20.000 2ch 44.1kHz 882000 samples
auo [info]:  x265として ".\exe_files\x265_3.5+109_x64.exe" を使用します。
auo [info]:  Opus Oggとして ".\exe_files\opusenc.exe" を使用します。
auo [info]:  mkvmergeとして ".\exe_files\mkvmerge.exe" を使用します。
auo [info]: converting YC48 -> i420i(16bit), using AVX AVX2
auo [info]: x265 options...
 --input-depth 16 --output-depth 12 --input-csp i420 --preset veryslow --tune animation --crf 28 --qcomp 0.8 --rc-lookahead
250 --aq-mode 0 --keyint -1 --bframes 16 --b-adapt 0 --bframe-bias 100 --no-sao --interlace tff --tu-intra-depth 1
--tu-inter-depth 1 --me dia --limit-refs 1 --limit-modes --ref 8 --colormatrix bt709 --colorprim bt709 --transfer bt709 --sar
4:3 --qg-size 8 --frame-threads 1 --no-cutree --pmode --pme --hevc-aq --fades --lowpass-dct --pbratio 1 --frames 480
--input-res 1440x540 --fps 24/1 -o "C:\Users\yuuki\Opia.1080i24.265" "-"
yuv  [info]: 1440x540 fps 24/1 i420p16 sar 4:3 unknown frame count
raw  [info]: output file: C:\Users\yuuki\Opia.1080i24.265
x265 [info]: HEVC encoder version 3.5+109-343ac2692
x265 [info]: build info [Windows][GCC 13.2.0][64 bit] 12bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
x265 [warning]: Support for interlaced video is experimental
x265 [info]: Main 12 profile, Level-4 (Main tier)
x265 [info]: Thread pool created using 12 threads
x265 [info]: Slices                              : 1
x265 [info]: frame threads / pool features       : 1 / wpp(9 rows)+pmode+pme 
x265 [info]: Interlaced field inputs             : tff
x265 [info]: Coding QT: max CU size, min CU size : 64 / 8
x265 [info]: Residual QT: max TU size, max depth : 32 / 1 inter / 1 intra
x265 [info]: ME / range / subpel / merge         : dia / 57 / 4 / 5
x265 [info]: Keyframe min / max / scenecut       : disabled
x265 [info]: Lookahead / bframes / badapt        : 250 / 16 / 0
x265 [info]: b-pyramid / weightp / weightb       : 1 / 1 / 1
x265 [info]: References / ref-limit  cu / depth  : 8 / off / on
x265 [info]: Rate Control / qCompress            : CRF-28.0 / 0.80
x265 [info]: tools: rect amp limit-modes rd=6 psy-rd=0.40 rdoq=2 psy-rdoq=1.00
x265 [info]: tools: rskip mode=1 signhide tmvp b-intra strong-intra-smoothing
x265 [info]: tools: deblock(tC=1:B=1)
x265 [info]: frame I:      4, Avg QP:24.96  kb/s: 1288.27 
x265 [info]: frame P:     28, Avg QP:27.72  kb/s: 601.41  
x265 [info]: frame B:    448, Avg QP:27.69  kb/s: 457.56  
x265 [info]: Weighted P-Frames: Y:35.7% UV:3.6%
x265 [info]: Weighted B-Frames: Y:39.5% UV:6.0%

encoded 480 frames in 88.12s (5.45 fps), 472.88 kb/s, Avg QP:27.67
auo [info]: CPU使用率: Aviutl: 1.69% / x265: 14.85%
auo [info]: Aviutl 平均フレーム取得時間: 18.713 ms
auo [info]: x265エンコード時間 : 0時間 1分28.8秒
auo [info]: Opus Ogg (v0.2) で音声エンコードを行います。 VBR ビットレート指定, 128kbps
auo [info]: mkvmerge (r81) でmuxを行います。 映像: on, 音声: on, tc:off, chap:off, 拡張モード:なし
auo [info]: 総エンコード時間   : 0時間 1分33.8秒

**Comment by rigaya** [comment]
HEVCのインタレ保持は、再生側が対応していない場合がありますので、再生側の問題の可能性が高いです。手元では、```--input-depth 16 --output-depth 12 --input-csp i420 --preset superfast --crf 28 --interlace tff``` のみで試したところ、mpc-beでソフトウェアデコードの場合は再生できました。

提示いただいたログに

> x265 [warning]: Support for interlaced video is experimental

と出ているように、HEVCのインタレ保持は再生互換性も低いです。基本的にはインタレを解除し--interlace tffを外してエンコードすることをお勧めします。

**Comment by resistorsytrus** [comment]
実は私もMPC-BEで再生したのですが、互換性の問題だったんですね。ありがとうございます!
